# Generated by Django 6.0.1 on 2026-01-21 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('items', models.JSONField(default=list, verbose_name='Items del Pedido')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
