# Generated by Django 6.0.1 on 2026-01-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comprobante',
            field=models.ImageField(default='', upload_to='comprobantes/', verbose_name='Comprobante de Pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción'),
        ),
    ]
